GET localhost:8080/
###

POST localhost:8080/reg
Content-Type: application/json

{
  "login": "User",
  "password": "Password",
  "confirm_password": "Password",
  "nickname": "User1",
  "avatar": "localhost/p1.png"
}

###

POST localhost:8080/login
Content-Type: application/json

{
  "login": "User1",
  "password": "Password"
}
###
